remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
google_analytics: G-FGJKN4HRMN
github:
  zip_url: https://github.com/Svxy/TnyavnTos-GTA5-Mod-Menu/releases/latest/download/TnyavnTosGTA5ModMenu.dll
  another_url: another value