remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-hacker
title: TnyavnTos GTA 5 Mod Menu
description: TnyavnTos GTA 5 Mod Menu is a protection and defense based mod menu for GTA 5, download today and inject with the included dll injector. (Now includes Nightclub Safe Loop)
show_downloads: true
google_analytics: G-FGJKN4HRMN
theme: jekyll-theme-hacker
github:
  zip_url: https://github.com/Svxy/TnyavnTos-GTA5-Mod-Menu/releases/latest/download/TnyavnTosGTA5ModMenu.dll
  another_url: another value