remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-midnight
title: TnyavnTos GTA 5 Mod Menu
description: TnyavnTos GTA 5 Mod Menu is a protection and defense based mod menu for GTA 5, download today and inject with the included dll injector.
show_downloads: true
google_analytics: G-FGJKN4HRMN
website: https://tnyavnto.com
basewebsite: /menu
permalink: 3/1/2023
github:
  zip_url: https://github.com/Svxy/TnyavnTos-GTA5-Mod-Menu/releases/latest/download/TnyavnTosGTA5ModMenu.dll
  repository_url: https://github.com/Svxy/TnyavnTos-GTA5-Mod-Menu
